### ISSUE TITLE
use of tags doesn't work very well with GitHub and pull-requests

### ISSUE THREAD

**Issue by brianjmurrell** [dgoodwin/tito#290] opened 2017-06-02 13:46 UTC
Let's say I have a tito repo of RPMs in the one-per-subdir format on GitHub.  I want to update an RPM that is in a subdir so I create a branch, do my work locally including testing that it builds, etc.  I then `tito tag` it and push up the branch and open a PR on it.

The project reviews the work, accepts it and merges it to master.

All good except that the tag that _tito_ created on the branch stays on the branch and doesn't get moved to master where the PR was merged to.

None of this is really all that surprising when you give it the time to think it through.  But I wonder what the best strategy is here considering how GitHub pull-requests work.

It seems like the best/most ideal solution would be a feature in GH that when accepting a PR the maintainer can merge (i.e. move) any tags on the branch that the PR is created from.  I'm not holding my breath though.

**Comment by jmrodri** [comment] 2017-06-02 14:02
I don't think that's how the tag was intended to be used. The tags are meant for a particular release of the software that ends up in an rpm. I would expect the changes to be done in a PR, have them merged to the project. THEN tag the project in master to release that particular package. 

Since `tito tag` simply uses a `git tag` behind the scenes they will work like any other `git tag`. Also tags are tied to commits and depending on how the PR is being merged the commit could change which means the tag is pointing to a dangling commit.

I'm not sure I completely understand your workflow though. Why are you tagging the branch and PR?

**Comment by dgoodwin** [comment] 2017-06-02 14:27
Tags are not per branch they just reference commits, technically if you push a tag, it's already repo wide, the commit just hasn't been merged into master yet and won't appear in it's history. Once the PR merges, you should see that tag in your git history for master, provided you did not make any changes to that commit in the PR. This leads to the point that PR's for tito commits don't really make sense, any change during review would break the tag, which was already pushed.

Normal tito workflow is to tag and push to master, no PRs involved, and treat tags as immutable. However technically, you should be able to do it with PRs you're just going to make a lot of work for yourself, with a lot of confusion and no real benefit. tito build --rpm --test is always there to verify the build works locally if needed.

**Comment by stevekuznetsov** [comment] 2017-06-02 14:29
We ran into this as well -- there's no way for someone to make a PR in which they tag something. You can't bring in a tag from a PR. This would be really nice -- we do something like this:

 - build artifacts from commit `x`
 - tag it as a release
 - test artifacts
 - if successful, push it all up

This looks a lot like the normal PR flow but we need to do it with escalated privileges since we can't add a tag to the repo using a PR.

**Comment by brianjmurrell** [comment] 2017-06-02 14:54
@dgoodwin:  Ahhh!  What you are saying makes complete sense.  I think the problem was that the maintainer squashed commits in the PR when merging, altering the sha1.

**Comment by dgoodwin** [comment] 2017-06-02 15:00
That'll do it!

Going to close as I don't think there's anything we can do here.

**Closed by dgoodwin** 2017-06-02 15:00 UTC

**Comment by xsuchy** [comment] 2017-06-02 15:07
@brianjmurrell if you want to build rpm for testing purposes from you branch, then run `tito build --rpm --test` and it will build packages without the need for tag.

**Comment by brianjmurrell** [comment] 2017-06-27 16:52
So, looking further into this, even when you don't squash when you merge on GH, the alternate strategy is to rebase and merge but that still changes the SHA, contrary to how traditional git does rebases:

https://help.github.com/articles/about-pull-request-merges/

> The rebase and merge behavior on GitHub deviates slightly from git rebase. Rebase and merge on GitHub will always update the committer information and create new commit SHAs, whereas git rebase outside of GitHub does not change the committer information when the rebase happens on top of an ancestor commit.

So the original premise of this ticket still stands I would say.  It's just not possible to create a PR for a tito commit and successfully merge that to master keeping the tito data (i.e. the tag) valid.  :-(

**Comment by dgoodwin** [comment] 2017-06-27 19:44
You would need to just merge, no rebase.

**Comment by brianjmurrell** [comment] 2017-06-27 20:01
Indeed.  But per the URL I included I don't believe GH has any option to do that in the UI.

**Comment by dgoodwin** [comment] 2017-06-27 23:37
Open PR, wait for merge, git push --tags should work provided you do not
use rebase locally at any point after creating your tag. I'd need to test
though but in any case, this is not workflow I would recommend.

**Comment by brianjmurrell** [comment] 2017-06-28 03:18
I can't see how that would be any more successful than pushing the tito tag to your PR and it getting lost when being landed with a rebase and merge.

Even if i wait for the PR to land before pushing the tag, it will have either landed with a squash or a rebase and so the sha1 of the landed commit will still be different than the sha1 in my local tree, where the tag is that I am trying to push.  Unless you are implicitly suggesting there is a git fetch in there to get my master up to date, which I then tito tag and push that tag.  Yeck, if so (no offensc intended).

The only workflow that seems to work is to pull PR to local and land the PR locally on master with a real merge and then just push the master branch up to GH.  Not really at all ideal, but that does seem to work.

I'm on the verge of calling GH's merging strategies a bug because of all of this.  Even if they want to continue their two strategies: squash and rebase, I think they should offer a third strategy to just do a proper merge, preserving committer and therefor the sha1.

**Comment by dgoodwin** [comment] 2017-06-28 10:01
If you put up a PR and someone presses merge, there is no automatic squash,
rebase, or change of Sha1, your commit goes in with the hash it had before,
after which you could push your tag.

In any case no matter what, this is all a recipie for trouble and again,
not something I would recommend. Tag and push to the repo directly.
